name: Deploy API to Cloud Run

on:
  push:
    branches: [ main ]
    paths:
      - 'api/**'
      - '.github/workflows/deploy-cloudrun.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Auth to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY_JSON }}

      - name: Configure gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Build & Push Image (Artifact Registry)
        run: |
          IMAGE="europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cloud-run/${{ secrets.GCP_SERVICE }}:${{ github.sha }}"
          gcloud builds submit api --tag "$IMAGE"

      - name: Deploy to Cloud Run
        run: |
          IMAGE="europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cloud-run/${{ secrets.GCP_SERVICE }}:${{ github.sha }}"
          gcloud run deploy "${{ secrets.GCP_SERVICE }}" \
            --image "$IMAGE" \
            --region "${{ secrets.GCP_REGION }}" \
            --platform managed \
            --allow-unauthenticated \
            --port 8080

      - name: Show Service URL
        run: |
          gcloud run services describe "${{ secrets.GCP_SERVICE }}" \
            --region "${{ secrets.GCP_REGION }}" \
            --format='value(status.url)'